if(keyboard_check_pressed(vk_numpad1))
{
	scr_weapon_switch(1);
}
if(keyboard_check_pressed(vk_numpad2))
{
	scr_weapon_switch(2);
}
if(keyboard_check_pressed(vk_numpad3))
{
	scr_weapon_switch(3);
}
if(keyboard_check_pressed(vk_numpad4))
{
	scr_weapon_switch(4);
}
if(keyboard_check_pressed(vk_numpad5))
{
	scr_weapon_switch(5);
}
if(keyboard_check_pressed(vk_numpad6))
{
	scr_weapon_switch(6);
}
if(keyboard_check_pressed(vk_numpad7))
{
	scr_weapon_switch(7);
}